# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

sensor:
  - platform: command_line
    name: Pi CPU Temperature
    unique_id: pi_cpu_temp
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: "{{ value | multiply(0.001) | round(1) }}"

mqtt:
  sensor:
    - name: leaf_battery_level
      unique_id: leaf_battery_level
      state_topic: "leaf/battery/percentage"
      unit_of_measurement: "%"
      device_class: battery
    
    - name: leaf_battery_connected
      unique_id: leaf_battery_connected
      state_topic: "leaf/battery/connected"
      device_class: battery
      
    - name: leaf_battery_charging
      unique_id: leaf_battery_charging
      state_topic: "leaf/battery/charging"
      device_class: battery
      
    - name: leaf_battery_cruisingRangeACOffKM
      unique_id: leaf_batter_cruisingRangeAcOffKM
      state_topic: "leaf/battery/cruisingRangeAcOffKm"
      device_class: distance
      
    - name: leaf_battery_cruisingRangeACOnKM
      unique_id: leaf_battery_cruisingRangeACOnKM
      state_topic: "leaf/battery/cruisingRangeAcOnKm"
      device_class: distance
      
    - name: leaf_climate_cabinTemperature
      unique_id: leaf_climate_cabinTemperature
      state_topic: "leaf/climate/cabinTemperatureC"
      unit_of_measurement: "°C"
      device_class: temperature
